// Generated by sim/matchups.ts from equal-cost duels. Do not edit; rerun it after changing unit stats.
import type { UnitType } from '../config';

export type Matchup = 'infantry' | 'trike' | 'tank' | 'rocket' | 'trooper' | 'sardaukar' | 'razor' | 'devastator' | 'raider' | 'artillery' | 'warrior' | 'fedaykin';

/**
 * MATCHUPS[key][a][b]: how an army of a fares against an equal-cost army of b in the open, from -1 (wiped out without
 * a scratch on b) to +1 (the reverse). Each fights for its own faction. key: Infantry Rockets on a's side, then b's
 * ('R' researched, '-' not).
 */
export const MATCHUPS: Record<string, Record<Matchup, Record<Matchup, number>>> = {
  '--': {
    infantry: { infantry: 0, trike: -0.54, tank: -0.52, rocket: -0.82, trooper: -0.36, sardaukar: -0.2, razor: -0.79, devastator: -0.4, raider: 0.78, artillery: 0.32, warrior: -0.22, fedaykin: 0.69 },
    trike: { infantry: 0.54, trike: 0, tank: -0.59, rocket: -0.5, trooper: -0.03, sardaukar: 0.59, razor: -0.21, devastator: -0.29, raider: -0.99, artillery: 0.4, warrior: 0.33, fedaykin: -0.28 },
    tank: { infantry: 0.52, trike: 0.59, tank: 0, rocket: 0.37, trooper: -0.72, sardaukar: -0.54, razor: 0.53, devastator: 0.19, raider: -0.82, artillery: 0.57, warrior: 0.23, fedaykin: -0.71 },
    rocket: { infantry: 0.82, trike: 0.5, tank: -0.37, rocket: 0, trooper: 0.24, sardaukar: 0.73, razor: -0.07, devastator: -0.4, raider: 0.23, artillery: 0.47, warrior: 0.82, fedaykin: -0.2 },
    trooper: { infantry: 0.36, trike: 0.03, tank: 0.72, rocket: -0.24, trooper: 0, sardaukar: 0.3, razor: -0.39, devastator: 0.8, raider: -0.96, artillery: 0.76, warrior: -0.23, fedaykin: 0.7 },
    sardaukar: { infantry: 0.2, trike: -0.59, tank: 0.54, rocket: -0.73, trooper: -0.3, sardaukar: 0, razor: -0.81, devastator: 0.35, raider: 0.83, artillery: 0.66, warrior: 0.05, fedaykin: 0.64 },
    razor: { infantry: 0.79, trike: 0.21, tank: -0.53, rocket: 0.07, trooper: 0.39, sardaukar: 0.81, razor: 0, devastator: -0.28, raider: -0.96, artillery: 0.52, warrior: 0.78, fedaykin: -0.34 },
    devastator: { infantry: 0.4, trike: 0.29, tank: -0.19, rocket: 0.4, trooper: -0.8, sardaukar: -0.35, razor: 0.28, devastator: 0, raider: -0.98, artillery: 0.51, warrior: 0.52, fedaykin: -0.79 },
    raider: { infantry: -0.78, trike: 0.99, tank: 0.83, rocket: -0.23, trooper: 0.96, sardaukar: -0.83, razor: 0.96, devastator: 0.98, raider: 0, artillery: 0.93, warrior: -0.85, fedaykin: -0.94 },
    artillery: { infantry: -0.32, trike: -0.4, tank: -0.57, rocket: -0.47, trooper: -0.76, sardaukar: -0.66, razor: -0.52, devastator: -0.51, raider: -0.93, artillery: 0, warrior: -0.54, fedaykin: -0.77 },
    warrior: { infantry: 0.22, trike: -0.33, tank: -0.23, rocket: -0.82, trooper: 0.23, sardaukar: -0.05, razor: -0.78, devastator: -0.52, raider: 0.85, artillery: 0.54, warrior: 0, fedaykin: 0.76 },
    fedaykin: { infantry: -0.69, trike: 0.28, tank: 0.71, rocket: 0.2, trooper: -0.7, sardaukar: -0.64, razor: 0.34, devastator: 0.79, raider: 0.94, artillery: 0.77, warrior: -0.76, fedaykin: 0 },
  },
  '-R': {
    infantry: { infantry: 0, trike: -0.54, tank: -0.52, rocket: -0.82, trooper: -0.36, sardaukar: -0.2, razor: -0.79, devastator: -0.4, raider: 0.78, artillery: 0.32, warrior: -0.22, fedaykin: 0.69 },
    trike: { infantry: 0.54, trike: 0, tank: -0.59, rocket: -0.5, trooper: -0.03, sardaukar: 0.59, razor: -0.21, devastator: -0.29, raider: -0.99, artillery: 0.4, warrior: 0.33, fedaykin: -0.28 },
    tank: { infantry: -0.65, trike: 0.59, tank: 0, rocket: 0.37, trooper: -0.72, sardaukar: -0.54, razor: 0.53, devastator: 0.19, raider: -0.82, artillery: 0.57, warrior: 0.23, fedaykin: -0.71 },
    rocket: { infantry: 0.72, trike: 0.5, tank: -0.37, rocket: 0, trooper: 0.24, sardaukar: 0.73, razor: -0.07, devastator: -0.4, raider: 0.23, artillery: 0.47, warrior: 0.82, fedaykin: -0.2 },
    trooper: { infantry: 0.36, trike: 0.03, tank: 0.72, rocket: -0.24, trooper: 0, sardaukar: 0.3, razor: -0.39, devastator: 0.8, raider: -0.96, artillery: 0.76, warrior: -0.23, fedaykin: 0.7 },
    sardaukar: { infantry: 0.2, trike: -0.59, tank: 0.54, rocket: -0.73, trooper: -0.3, sardaukar: 0, razor: -0.81, devastator: 0.35, raider: 0.83, artillery: 0.66, warrior: 0.05, fedaykin: 0.64 },
    razor: { infantry: 0.79, trike: 0.21, tank: -0.53, rocket: 0.07, trooper: 0.39, sardaukar: 0.81, razor: 0, devastator: -0.28, raider: -0.96, artillery: 0.52, warrior: 0.78, fedaykin: -0.34 },
    devastator: { infantry: -0.75, trike: 0.29, tank: -0.19, rocket: 0.4, trooper: -0.8, sardaukar: -0.35, razor: 0.28, devastator: 0, raider: -0.98, artillery: 0.51, warrior: 0.52, fedaykin: -0.79 },
    raider: { infantry: -0.78, trike: 0.99, tank: 0.83, rocket: -0.23, trooper: 0.96, sardaukar: -0.83, razor: 0.96, devastator: 0.98, raider: 0, artillery: 0.93, warrior: -0.85, fedaykin: -0.94 },
    artillery: { infantry: -0.73, trike: -0.4, tank: -0.57, rocket: -0.47, trooper: -0.76, sardaukar: -0.66, razor: -0.52, devastator: -0.51, raider: -0.93, artillery: 0, warrior: -0.54, fedaykin: -0.77 },
    warrior: { infantry: 0.22, trike: -0.33, tank: -0.23, rocket: -0.82, trooper: 0.23, sardaukar: -0.05, razor: -0.78, devastator: -0.52, raider: 0.85, artillery: 0.54, warrior: 0, fedaykin: 0.76 },
    fedaykin: { infantry: -0.69, trike: 0.28, tank: 0.71, rocket: 0.2, trooper: -0.7, sardaukar: -0.64, razor: 0.34, devastator: 0.79, raider: 0.94, artillery: 0.77, warrior: -0.76, fedaykin: 0 },
  },
  'R-': {
    infantry: { infantry: 0, trike: -0.54, tank: 0.65, rocket: -0.72, trooper: -0.36, sardaukar: -0.2, razor: -0.79, devastator: 0.75, raider: 0.78, artillery: 0.73, warrior: -0.22, fedaykin: 0.69 },
    trike: { infantry: 0.54, trike: 0, tank: -0.59, rocket: -0.5, trooper: -0.03, sardaukar: 0.59, razor: -0.21, devastator: -0.29, raider: -0.99, artillery: 0.4, warrior: 0.33, fedaykin: -0.28 },
    tank: { infantry: 0.52, trike: 0.59, tank: 0, rocket: 0.37, trooper: -0.72, sardaukar: -0.54, razor: 0.53, devastator: 0.19, raider: -0.82, artillery: 0.57, warrior: 0.23, fedaykin: -0.71 },
    rocket: { infantry: 0.82, trike: 0.5, tank: -0.37, rocket: 0, trooper: 0.24, sardaukar: 0.73, razor: -0.07, devastator: -0.4, raider: 0.23, artillery: 0.47, warrior: 0.82, fedaykin: -0.2 },
    trooper: { infantry: 0.36, trike: 0.03, tank: 0.72, rocket: -0.24, trooper: 0, sardaukar: 0.3, razor: -0.39, devastator: 0.8, raider: -0.96, artillery: 0.76, warrior: -0.23, fedaykin: 0.7 },
    sardaukar: { infantry: 0.2, trike: -0.59, tank: 0.54, rocket: -0.73, trooper: -0.3, sardaukar: 0, razor: -0.81, devastator: 0.35, raider: 0.83, artillery: 0.66, warrior: 0.05, fedaykin: 0.64 },
    razor: { infantry: 0.79, trike: 0.21, tank: -0.53, rocket: 0.07, trooper: 0.39, sardaukar: 0.81, razor: 0, devastator: -0.28, raider: -0.96, artillery: 0.52, warrior: 0.78, fedaykin: -0.34 },
    devastator: { infantry: 0.4, trike: 0.29, tank: -0.19, rocket: 0.4, trooper: -0.8, sardaukar: -0.35, razor: 0.28, devastator: 0, raider: -0.98, artillery: 0.51, warrior: 0.52, fedaykin: -0.79 },
    raider: { infantry: -0.78, trike: 0.99, tank: 0.83, rocket: -0.23, trooper: 0.96, sardaukar: -0.83, razor: 0.96, devastator: 0.98, raider: 0, artillery: 0.93, warrior: -0.85, fedaykin: -0.94 },
    artillery: { infantry: -0.32, trike: -0.4, tank: -0.57, rocket: -0.47, trooper: -0.76, sardaukar: -0.66, razor: -0.52, devastator: -0.51, raider: -0.93, artillery: 0, warrior: -0.54, fedaykin: -0.77 },
    warrior: { infantry: 0.22, trike: -0.33, tank: -0.23, rocket: -0.82, trooper: 0.23, sardaukar: -0.05, razor: -0.78, devastator: -0.52, raider: 0.85, artillery: 0.54, warrior: 0, fedaykin: 0.76 },
    fedaykin: { infantry: -0.69, trike: 0.28, tank: 0.71, rocket: 0.2, trooper: -0.7, sardaukar: -0.64, razor: 0.34, devastator: 0.79, raider: 0.94, artillery: 0.77, warrior: -0.76, fedaykin: 0 },
  },
  'RR': {
    infantry: { infantry: 0, trike: -0.54, tank: 0.65, rocket: -0.72, trooper: -0.36, sardaukar: -0.2, razor: -0.79, devastator: 0.75, raider: 0.78, artillery: 0.73, warrior: -0.22, fedaykin: 0.69 },
    trike: { infantry: 0.54, trike: 0, tank: -0.59, rocket: -0.5, trooper: -0.03, sardaukar: 0.59, razor: -0.21, devastator: -0.29, raider: -0.99, artillery: 0.4, warrior: 0.33, fedaykin: -0.28 },
    tank: { infantry: -0.65, trike: 0.59, tank: 0, rocket: 0.37, trooper: -0.72, sardaukar: -0.54, razor: 0.53, devastator: 0.19, raider: -0.82, artillery: 0.57, warrior: 0.23, fedaykin: -0.71 },
    rocket: { infantry: 0.72, trike: 0.5, tank: -0.37, rocket: 0, trooper: 0.24, sardaukar: 0.73, razor: -0.07, devastator: -0.4, raider: 0.23, artillery: 0.47, warrior: 0.82, fedaykin: -0.2 },
    trooper: { infantry: 0.36, trike: 0.03, tank: 0.72, rocket: -0.24, trooper: 0, sardaukar: 0.3, razor: -0.39, devastator: 0.8, raider: -0.96, artillery: 0.76, warrior: -0.23, fedaykin: 0.7 },
    sardaukar: { infantry: 0.2, trike: -0.59, tank: 0.54, rocket: -0.73, trooper: -0.3, sardaukar: 0, razor: -0.81, devastator: 0.35, raider: 0.83, artillery: 0.66, warrior: 0.05, fedaykin: 0.64 },
    razor: { infantry: 0.79, trike: 0.21, tank: -0.53, rocket: 0.07, trooper: 0.39, sardaukar: 0.81, razor: 0, devastator: -0.28, raider: -0.96, artillery: 0.52, warrior: 0.78, fedaykin: -0.34 },
    devastator: { infantry: -0.75, trike: 0.29, tank: -0.19, rocket: 0.4, trooper: -0.8, sardaukar: -0.35, razor: 0.28, devastator: 0, raider: -0.98, artillery: 0.51, warrior: 0.52, fedaykin: -0.79 },
    raider: { infantry: -0.78, trike: 0.99, tank: 0.83, rocket: -0.23, trooper: 0.96, sardaukar: -0.83, razor: 0.96, devastator: 0.98, raider: 0, artillery: 0.93, warrior: -0.85, fedaykin: -0.94 },
    artillery: { infantry: -0.73, trike: -0.4, tank: -0.57, rocket: -0.47, trooper: -0.76, sardaukar: -0.66, razor: -0.52, devastator: -0.51, raider: -0.93, artillery: 0, warrior: -0.54, fedaykin: -0.77 },
    warrior: { infantry: 0.22, trike: -0.33, tank: -0.23, rocket: -0.82, trooper: 0.23, sardaukar: -0.05, razor: -0.78, devastator: -0.52, raider: 0.85, artillery: 0.54, warrior: 0, fedaykin: 0.76 },
    fedaykin: { infantry: -0.69, trike: 0.28, tank: 0.71, rocket: 0.2, trooper: -0.7, sardaukar: -0.64, razor: 0.34, devastator: 0.79, raider: 0.94, artillery: 0.77, warrior: -0.76, fedaykin: 0 },
  },
};

export const MATCHUP_TYPES: UnitType[] = ["infantry","trike","tank","rocket","trooper","sardaukar","razor","devastator","raider","artillery","warrior","fedaykin"];
