// Generated by sim/matchups.ts from equal-cost duels. Do not edit; rerun it after changing unit stats.
import type { UnitType } from '../config';

export type Matchup = 'infantry' | 'trike' | 'tank' | 'rocket';

/**
 * MATCHUPS[key][a][b]: how an army of a fares against an equal-cost army of b in the open, from -1 (wiped out without
 * a scratch on b) to +1 (the reverse). key: Infantry Rockets on a's side, then b's ('R' researched, '-' not).
 */
export const MATCHUPS: Record<string, Record<Matchup, Record<Matchup, number>>> = {
  '--': {
    infantry: { infantry: 0, trike: 0.03, tank: 0.18, rocket: -0.83 },
    trike: { infantry: -0.03, trike: 0, tank: -0.59, rocket: -0.86 },
    tank: { infantry: -0.18, trike: 0.59, tank: 0, rocket: 0.17 },
    rocket: { infantry: 0.83, trike: 0.86, tank: -0.16, rocket: 0 },
  },
  '-R': {
    infantry: { infantry: 0.04, trike: 0.01, tank: 0.17, rocket: -0.83 },
    trike: { infantry: -0.01, trike: 0, tank: -0.59, rocket: -0.86 },
    tank: { infantry: -0.7, trike: 0.6, tank: 0.01, rocket: 0.14 },
    rocket: { infantry: 0.74, trike: 0.87, tank: -0.14, rocket: 0.02 },
  },
  'R-': {
    infantry: { infantry: -0.04, trike: 0.01, tank: 0.71, rocket: -0.74 },
    trike: { infantry: 0, trike: 0, tank: -0.6, rocket: -0.87 },
    tank: { infantry: -0.16, trike: 0.6, tank: -0.01, rocket: 0.14 },
    rocket: { infantry: 0.83, trike: 0.86, tank: -0.14, rocket: -0.02 },
  },
  'RR': {
    infantry: { infantry: 0, trike: -0.01, tank: 0.71, rocket: -0.76 },
    trike: { infantry: 0.01, trike: 0, tank: -0.6, rocket: -0.87 },
    tank: { infantry: -0.7, trike: 0.6, tank: 0, rocket: 0.15 },
    rocket: { infantry: 0.76, trike: 0.87, tank: -0.15, rocket: 0 },
  },
};

export const MATCHUP_TYPES: UnitType[] = ["infantry","trike","tank","rocket"];
