// Generated by sim/matchups.ts from equal-cost duels. Do not edit; rerun it after changing unit stats.
import type { UnitType } from '../config';

export type Matchup = 'infantry' | 'trike' | 'tank' | 'rocket' | 'trooper' | 'sardaukar' | 'razor' | 'devastator' | 'raider' | 'artillery';

/**
 * MATCHUPS[key][a][b]: how an army of a fares against an equal-cost army of b in the open, from -1 (wiped out without
 * a scratch on b) to +1 (the reverse). Each fights for its own faction. key: Infantry Rockets on a's side, then b's
 * ('R' researched, '-' not).
 */
export const MATCHUPS: Record<string, Record<Matchup, Record<Matchup, number>>> = {
  '--': {
    infantry: { infantry: 0, trike: -0.54, tank: -0.52, rocket: -0.82, trooper: -0.32, sardaukar: -0.2, razor: -0.79, devastator: -0.4, raider: 0.76, artillery: 0.3 },
    trike: { infantry: 0.54, trike: 0, tank: -0.59, rocket: -0.49, trooper: -0.08, sardaukar: 0.59, razor: -0.21, devastator: -0.29, raider: -0.99, artillery: 0.4 },
    tank: { infantry: 0.52, trike: 0.59, tank: 0, rocket: 0.38, trooper: -0.72, sardaukar: -0.54, razor: 0.53, devastator: 0.19, raider: -0.76, artillery: 0.57 },
    rocket: { infantry: 0.82, trike: 0.49, tank: -0.38, rocket: 0, trooper: 0.08, sardaukar: 0.73, razor: 0.11, devastator: -0.4, raider: 0.16, artillery: 0.48 },
    trooper: { infantry: 0.32, trike: 0.08, tank: 0.72, rocket: -0.08, trooper: 0, sardaukar: 0.3, razor: -0.41, devastator: 0.78, raider: -0.96, artillery: 0.75 },
    sardaukar: { infantry: 0.2, trike: -0.59, tank: 0.54, rocket: -0.73, trooper: -0.3, sardaukar: 0, razor: -0.81, devastator: 0.35, raider: 0.81, artillery: 0.66 },
    razor: { infantry: 0.79, trike: 0.21, tank: -0.53, rocket: -0.11, trooper: 0.41, sardaukar: 0.81, razor: 0, devastator: -0.28, raider: -0.96, artillery: 0.5 },
    devastator: { infantry: 0.4, trike: 0.29, tank: -0.19, rocket: 0.4, trooper: -0.78, sardaukar: -0.35, razor: 0.28, devastator: 0, raider: -0.98, artillery: 0.51 },
    raider: { infantry: -0.76, trike: 0.99, tank: 0.76, rocket: -0.16, trooper: 0.96, sardaukar: -0.81, razor: 0.96, devastator: 0.98, raider: 0, artillery: 0.93 },
    artillery: { infantry: -0.3, trike: -0.4, tank: -0.57, rocket: -0.48, trooper: -0.75, sardaukar: -0.66, razor: -0.5, devastator: -0.51, raider: -0.93, artillery: 0 },
  },
  '-R': {
    infantry: { infantry: 0, trike: -0.54, tank: -0.52, rocket: -0.82, trooper: -0.32, sardaukar: -0.2, razor: -0.79, devastator: -0.4, raider: 0.76, artillery: 0.3 },
    trike: { infantry: 0.54, trike: 0, tank: -0.59, rocket: -0.49, trooper: -0.08, sardaukar: 0.59, razor: -0.21, devastator: -0.29, raider: -0.99, artillery: 0.4 },
    tank: { infantry: -0.65, trike: 0.59, tank: 0, rocket: 0.38, trooper: -0.72, sardaukar: -0.54, razor: 0.53, devastator: 0.19, raider: -0.76, artillery: 0.57 },
    rocket: { infantry: 0.58, trike: 0.49, tank: -0.38, rocket: 0, trooper: 0.08, sardaukar: 0.73, razor: 0.11, devastator: -0.4, raider: 0.16, artillery: 0.48 },
    trooper: { infantry: 0.32, trike: 0.08, tank: 0.72, rocket: -0.08, trooper: 0, sardaukar: 0.3, razor: -0.41, devastator: 0.78, raider: -0.96, artillery: 0.75 },
    sardaukar: { infantry: 0.2, trike: -0.59, tank: 0.54, rocket: -0.73, trooper: -0.3, sardaukar: 0, razor: -0.81, devastator: 0.35, raider: 0.81, artillery: 0.66 },
    razor: { infantry: 0.79, trike: 0.21, tank: -0.53, rocket: -0.11, trooper: 0.41, sardaukar: 0.81, razor: 0, devastator: -0.28, raider: -0.96, artillery: 0.5 },
    devastator: { infantry: -0.75, trike: 0.29, tank: -0.19, rocket: 0.4, trooper: -0.78, sardaukar: -0.35, razor: 0.28, devastator: 0, raider: -0.98, artillery: 0.51 },
    raider: { infantry: -0.76, trike: 0.99, tank: 0.76, rocket: -0.16, trooper: 0.96, sardaukar: -0.81, razor: 0.96, devastator: 0.98, raider: 0, artillery: 0.93 },
    artillery: { infantry: -0.73, trike: -0.4, tank: -0.57, rocket: -0.48, trooper: -0.75, sardaukar: -0.66, razor: -0.5, devastator: -0.51, raider: -0.93, artillery: 0 },
  },
  'R-': {
    infantry: { infantry: 0, trike: -0.54, tank: 0.65, rocket: -0.58, trooper: -0.32, sardaukar: -0.2, razor: -0.79, devastator: 0.75, raider: 0.76, artillery: 0.73 },
    trike: { infantry: 0.54, trike: 0, tank: -0.59, rocket: -0.49, trooper: -0.08, sardaukar: 0.59, razor: -0.21, devastator: -0.29, raider: -0.99, artillery: 0.4 },
    tank: { infantry: 0.52, trike: 0.59, tank: 0, rocket: 0.38, trooper: -0.72, sardaukar: -0.54, razor: 0.53, devastator: 0.19, raider: -0.76, artillery: 0.57 },
    rocket: { infantry: 0.82, trike: 0.49, tank: -0.38, rocket: 0, trooper: 0.08, sardaukar: 0.73, razor: 0.11, devastator: -0.4, raider: 0.16, artillery: 0.48 },
    trooper: { infantry: 0.32, trike: 0.08, tank: 0.72, rocket: -0.08, trooper: 0, sardaukar: 0.3, razor: -0.41, devastator: 0.78, raider: -0.96, artillery: 0.75 },
    sardaukar: { infantry: 0.2, trike: -0.59, tank: 0.54, rocket: -0.73, trooper: -0.3, sardaukar: 0, razor: -0.81, devastator: 0.35, raider: 0.81, artillery: 0.66 },
    razor: { infantry: 0.79, trike: 0.21, tank: -0.53, rocket: -0.11, trooper: 0.41, sardaukar: 0.81, razor: 0, devastator: -0.28, raider: -0.96, artillery: 0.5 },
    devastator: { infantry: 0.4, trike: 0.29, tank: -0.19, rocket: 0.4, trooper: -0.78, sardaukar: -0.35, razor: 0.28, devastator: 0, raider: -0.98, artillery: 0.51 },
    raider: { infantry: -0.76, trike: 0.99, tank: 0.76, rocket: -0.16, trooper: 0.96, sardaukar: -0.81, razor: 0.96, devastator: 0.98, raider: 0, artillery: 0.93 },
    artillery: { infantry: -0.3, trike: -0.4, tank: -0.57, rocket: -0.48, trooper: -0.75, sardaukar: -0.66, razor: -0.5, devastator: -0.51, raider: -0.93, artillery: 0 },
  },
  'RR': {
    infantry: { infantry: 0, trike: -0.54, tank: 0.65, rocket: -0.58, trooper: -0.32, sardaukar: -0.2, razor: -0.79, devastator: 0.75, raider: 0.76, artillery: 0.73 },
    trike: { infantry: 0.54, trike: 0, tank: -0.59, rocket: -0.49, trooper: -0.08, sardaukar: 0.59, razor: -0.21, devastator: -0.29, raider: -0.99, artillery: 0.4 },
    tank: { infantry: -0.65, trike: 0.59, tank: 0, rocket: 0.38, trooper: -0.72, sardaukar: -0.54, razor: 0.53, devastator: 0.19, raider: -0.76, artillery: 0.57 },
    rocket: { infantry: 0.58, trike: 0.49, tank: -0.38, rocket: 0, trooper: 0.08, sardaukar: 0.73, razor: 0.11, devastator: -0.4, raider: 0.16, artillery: 0.48 },
    trooper: { infantry: 0.32, trike: 0.08, tank: 0.72, rocket: -0.08, trooper: 0, sardaukar: 0.3, razor: -0.41, devastator: 0.78, raider: -0.96, artillery: 0.75 },
    sardaukar: { infantry: 0.2, trike: -0.59, tank: 0.54, rocket: -0.73, trooper: -0.3, sardaukar: 0, razor: -0.81, devastator: 0.35, raider: 0.81, artillery: 0.66 },
    razor: { infantry: 0.79, trike: 0.21, tank: -0.53, rocket: -0.11, trooper: 0.41, sardaukar: 0.81, razor: 0, devastator: -0.28, raider: -0.96, artillery: 0.5 },
    devastator: { infantry: -0.75, trike: 0.29, tank: -0.19, rocket: 0.4, trooper: -0.78, sardaukar: -0.35, razor: 0.28, devastator: 0, raider: -0.98, artillery: 0.51 },
    raider: { infantry: -0.76, trike: 0.99, tank: 0.76, rocket: -0.16, trooper: 0.96, sardaukar: -0.81, razor: 0.96, devastator: 0.98, raider: 0, artillery: 0.93 },
    artillery: { infantry: -0.73, trike: -0.4, tank: -0.57, rocket: -0.48, trooper: -0.75, sardaukar: -0.66, razor: -0.5, devastator: -0.51, raider: -0.93, artillery: 0 },
  },
};

export const MATCHUP_TYPES: UnitType[] = ["infantry","trike","tank","rocket","trooper","sardaukar","razor","devastator","raider","artillery"];
