// Measures how each combat unit type fares against each other one, and writes src/game/matchups.ts, which the AI
// uses to pick counters. Rerun after changing unit stats: npx tsx sim/matchups.ts
//
// Each matchup is an equal-cost duel in open ground (both armies attack-move at each other), played on a few maps
// with both sides swapped, then averaged with the mirrored matchup. The score is (value A has left - value B has
// left) / starting value: +1 means A won without a scratch, -1 the reverse. Done four times: with and without
// Infantry Rockets on each side.
import * as THREE from 'three';
import { writeFileSync } from 'node:fs';
import { Game } from '../src/game/game';
import { UNITS, type Team, type UnitType } from '../src/config';

const TYPES: UnitType[] = ['infantry', 'trike', 'tank', 'rocket'];
const BUDGET = 4000;
const SEEDS = [1003, 1007, 1012];

function duel(a: UnitType, b: UnitType, rocketsA: boolean, rocketsB: boolean, seed: number, swap: boolean): number {
  const g = new Game(new THREE.Scene(), new THREE.PerspectiveCamera(), 64, seed);
  for (const u of [...g.units]) {
    u.hp = 0;
    (g as unknown as { kill(e: unknown, by: null): void }).kill(u, null);
  }
  const [ta, tb]: Team[] = swap ? [1, 0] : [0, 1];
  if (rocketsA) g.teams[ta].upgrades.add('rockets');
  if (rocketsB) g.teams[tb].upgrades.add('rockets');
  const m = g.map;
  const mid = Math.round(m.size / 2);
  const spawn = (team: Team, type: UnitType, row: number, dir: number) => {
    const n = Math.round(BUDGET / UNITS[type].cost);
    for (let k = 0; k < n; k++) {
      const c = m.nearestCell(mid - 8 + (k % 16), row + Math.floor(k / 16) * dir, (x, z) => m.canEnter(x, z, 'vehicle'), 12)!;
      const u = g.spawnUnit(type, team, m.center(c.cx), m.center(c.cz));
      u.command(g, { kind: 'amove', x: m.center(mid), z: m.center(row - dir * 30) });
    }
  };
  spawn(ta, a, mid - 10, -1);
  spawn(tb, b, mid + 10, 1);
  const value = (t: Team) => g.units.filter((u) => u.team === t).reduce((s, u) => s + u.def.cost * (u.hp / u.maxHp), 0);
  const start = Math.min(value(ta), value(tb));
  while (g.time < 120 && g.units.some((u) => u.team === ta) && g.units.some((u) => u.team === tb)) g.update(0.05);
  return (value(ta) - value(tb)) / start;
}

const table: Record<string, Record<UnitType, Partial<Record<UnitType, number>>>> = {};
for (const ra of [false, true]) {
  for (const rb of [false, true]) {
    const key = `${ra ? 'R' : '-'}${rb ? 'R' : '-'}`;
    const t = (table[key] = {} as Record<UnitType, Partial<Record<UnitType, number>>>);
    for (const a of TYPES) {
      t[a] = {};
      for (const b of TYPES) {
        let sum = 0;
        let n = 0;
        for (const seed of SEEDS) for (const swap of [false, true]) {
          sum += duel(a, b, ra, rb, seed, swap);
          n++;
        }
        t[a][b] = Math.round((sum / n) * 100) / 100;
      }
      console.log(key, a.padEnd(9), TYPES.map((b) => `${b} ${t[a][b]!.toFixed(2).padStart(5)}`).join('   '));
    }
  }
}

// A fight is zero-sum, so a vs b must be -(b vs a). The raw duels aren't quite (the two armies start on different
// ground), so average each pair with its mirror; a type against itself comes out 0.
const raw = JSON.parse(JSON.stringify(table)) as typeof table;
for (const key of Object.keys(table)) {
  const mirror = key[1] + key[0];
  for (const a of TYPES) for (const b of TYPES) table[key][a][b] = Math.round(((raw[key][a][b]! - raw[mirror][b][a]!) / 2) * 100) / 100;
}

const body = Object.entries(table).map(([k, t]) => `  '${k}': {\n${TYPES.map((a) => `    ${a}: { ${TYPES.map((b) => `${b}: ${t[a][b]}`).join(', ')} },`).join('\n')}\n  },`).join('\n');
writeFileSync(new URL('../src/game/matchups.ts', import.meta.url), `// Generated by sim/matchups.ts from equal-cost duels. Do not edit; rerun it after changing unit stats.
import type { UnitType } from '../config';

export type Matchup = 'infantry' | 'trike' | 'tank' | 'rocket';

/**
 * MATCHUPS[key][a][b]: how an army of a fares against an equal-cost army of b in the open, from -1 (wiped out without
 * a scratch on b) to +1 (the reverse). key: Infantry Rockets on a's side, then b's ('R' researched, '-' not).
 */
export const MATCHUPS: Record<string, Record<Matchup, Record<Matchup, number>>> = {
${body}
};

export const MATCHUP_TYPES: UnitType[] = ${JSON.stringify(TYPES)};
`);
console.log('wrote src/game/matchups.ts');
